#-------------------------------------------------------------------------------------------------------
# Copyright (c) 2021 ChakraCore Project Contributors. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
#-------------------------------------------------------------------------------------------------------

trigger:
- master
- release/*

jobs:
  - job: Style
    timeoutInMinutes: 10

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: tools/StyleChecks/check_copyright.sh
      displayName: "Copyright Check"

    - script: tools/StyleChecks/check_ascii.sh
      displayName: "Ascii Check"

    - script: tools/StyleChecks/check_eol.sh
      displayName: "EOL Check"

    - script: tools/StyleChecks/check_tabs.sh
      displayName: "Tab Check"

  - job: MSVC
    timeoutInMinutes: 120
    pool:
      vmImage: 'windows-latest'
    strategy:
      maxParallel: 4
      matrix:
        x86.Debug:
          build_type: 'debug'
          target: 'x86'
          special_build: ''
          do_test: true
          test_tags: ''
        x86.Test:
          build_type: 'test'
          target: 'x86'
          special_build: ''
          do_test: true
          test_tags: '--include-slow'
        x86.NoJit:
          build_type: 'debug'
          target: 'x86'
          special_build: '"/p:BuildJIT=false"'
          do_test: true
          test_tags: '-disablejit'
        x86.Release:
          build_type: 'release'
          target: 'x86'
          special_build: ''
          do_test: false
          test_tags: ''
        x64.Debug:
          build_type: 'debug'
          target: 'x64'
          special_build: ''
          do_test: true
          test_tags: ''
        x64.Test:
          build_type: 'test'
          target: 'x64'
          special_build: ''
          do_test: true
          test_tags: '--include-slow'
        x64.Release:
          build_type: 'release'
          target: 'x64'
          special_build: ''
          do_test: false
          test_tags: ''
      
    steps:
    - script: test\ci.buildone.cmd %TARGET% %BUILD% %SPECIAL%
      displayName: 'Build'
      env:
        TARGET: $(target)
        BUILD: $(build_type)
        SPECIAL: $(special_build)

    - script: test\ci.testone.cmd %TARGET% %BUILD% %TEST_TAGS%
      displayName: 'Test'
      condition: eq(variables['do_test'], true)
      env:
        TARGET: $(target)
        BUILD: $(build_type)
        TEST_TAGS: ${test_tags}
